spring:

    security:
        oauth2:
            client:
                registration:
                    facebook :
                        client-id : 2885296784893597
                        clientSecret : b6445b35df28d788faec3e28b5d6e0f1
                    google :
                        clien-id: 809507897474-oh43b99ievlqvb7h10eekbj0trl07rec.apps.googleusercontent.com
                        clientSecret: iMHVSqzwJhnROfu3Olfo3J_u


custom:
    oauth2:
        kakao :
            client-id: 420394